services:
  him-ai:
    build:
      context: ./HIM.Microservices/HIM.AiService
    restart: always
    environment:
      - AiSettings__ChatProvider=Gemini
      - AiSettings__Groq__ApiKey=${GROQ_API_KEY}
      - AiSettings__Groq__ModelId=llama-3.3-70b-versatile
      - AiSettings__Groq__Endpoint=https://api.groq.com/openai/v1
      - AiSettings__Gemini__ApiKey=${GEMINI_API_KEY}
      - AiSettings__Gemini__ModelId=gemini-3.1-flash-lite
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./cache:/app/cache
      - ./HIM.Microservices/HIM.AiService/knowledge-base.json:/app/knowledge-base.json
  
  him-gateway:
    build:
      context: ./HIM.Gateway
    ports:
      - "22:22" # Public port 22 -> docker port 22
    environment:
      - SshSettings__Port=22
      - AiServiceSettings__BaseUrl=http://him-ai:8080
      - TERM=xterm-256color
      - DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION=true
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./keys:/app/keys # Persist hostkeys on the vps host machine
    depends_on:
      - him-ai
    restart: always